### ISSUE TITLE
Cognito auth without AWS cli profile

### ISSUE THREAD

**Issue by theharold** [zamzterz/cognito-demo#1]
When there is no aws credentials setup on your machine. The following error is encountered

(cognito-demo) [user@home cognito-demo]$ python cli.py 12d27tlcvhrq vim.pat
Password: 
Traceback (most recent call last):
  File "cli.py", line 59, in <module>
    auth_response = authenticate()
  File "cli.py", line 18, in authenticate
    ClientId=client_id,
  File "/home/user/projects/virtualenvs/cognito-demo/lib64/python3.6/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/user/projects/virtualenvs/cognito-demo/lib64/python3.6/site-packages/botocore/client.py", line 622, in _make_api_call
    operation_model, request_dict, request_context)
  File "/home/user/projects/virtualenvs/cognito-demo/lib64/python3.6/site-packages/botocore/client.py", line 641, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/home/user/projects/virtualenvs/cognito-demo/lib64/python3.6/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/home/user/projects/virtualenvs/cognito-demo/lib64/python3.6/site-packages/botocore/endpoint.py", line 132, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/home/user/projects/virtualenvs/cognito-demo/lib64/python3.6/site-packages/botocore/endpoint.py", line 116, in create_request
    operation_name=operation_model.name)
  File "/home/user/projects/virtualenvs/cognito-demo/lib64/python3.6/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/user/projects/virtualenvs/cognito-demo/lib64/python3.6/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/home/user/projects/virtualenvs/cognito-demo/lib64/python3.6/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/home/user/projects/virtualenvs/cognito-demo/lib64/python3.6/site-packages/botocore/signers.py", line 90, in handler
    return self.sign(operation_name, request)
  File "/home/user/projects/virtualenvs/cognito-demo/lib64/python3.6/site-packages/botocore/signers.py", line 160, in sign
    auth.add_auth(request)
  File "/home/user/projects/virtualenvs/cognito-demo/lib64/python3.6/site-packages/botocore/auth.py", line 357, in add_auth
    raise NoCredentialsError
botocore.exceptions.NoCredentialsError: Unable to locate credentials

**Comment by theharold** [comment]
boto3 libraries are trying to sign the request to aws, but this request is not supposed to be signed. To prevent that, create the identity pool client with a config that specifies no signing

**Comment by theharold** [comment]
The below is the changes made to cli.py. I don't think I've permissions to create a pull request.

import json
import sys
from getpass import getpass
from botocore.config import Config
from botocore import UNSIGNED

import boto3

cognito_client = boto3.client('cognito-idp', region_name='eu-west-1', config=Config(signature_version=UNSIGNED))


def authenticate():
    response = None
    while not response:
        try:
            password = getpass()
            response = cognito_client.initiate_auth(
                AuthFlow='USER_PASSWORD_AUTH',
                AuthParameters={'USERNAME': username, 'PASSWORD': password},
                ClientId=client_id,
            )
        except cognito_client.exceptions.NotAuthorizedException:
            print('Incorrect password, please try again.')
            pass

    return response
